<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5806" started-at="2019-07-09T00:27:52Z" finished-at="2019-07-09T00:27:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5806" started-at="2019-07-09T00:27:52Z" finished-at="2019-07-09T00:27:58Z">
      <class name="tests.WeatherTest">
        <test-method status="FAIL" signature="getForeCast()[pri:0, instance:tests.WeatherTest@445b84c0]" name="getForeCast" duration-ms="4113" started-at="2019-07-09T10:27:52Z" finished-at="2019-07-09T10:27:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ The status code is valid expected [200] but found [403]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError:  The status code is valid expected [200] but found [403]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at tests.WeatherTest.getForeCast(WeatherTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getForeCast -->
        <test-method status="PASS" signature="getStateCode()[pri:0, instance:tests.WeatherTest@445b84c0]" name="getStateCode" duration-ms="1669" started-at="2019-07-09T10:27:56Z" finished-at="2019-07-09T10:27:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getStateCode -->
      </class> <!-- tests.WeatherTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
